namespace LTU.SearchEngine.Backend.Core.Model.ValueObjects.QueryNodes;


/// <summary>
/// Represents a leaf node in the query tree containing a sequence of tokens that form an exact search phrase.
/// </summary>
/// <typeparam name="T">The return type produced by a visitor during tree traversal.</typeparam>
/// <remarks>
/// A PhraseNode is used to represent quoted strings from the user input, ensuring that the <br />
/// included tokens are treated as a single, ordered unit during the search process.
/// </remarks>
public class PhraseNode<T> : QueryNode<T>
{
	public List<ExtractedQueryToken> Phrase { get; }

	public PhraseNode(List<ExtractedQueryToken> phrase)
	{
		Phrase = phrase ??
			throw new ArgumentNullException(nameof(phrase), "must have a value.");
	}

	/// <summary>Accepts a visitor to process the phrase node.</summary>
	/// <param name="visitor">The <see cref="IQueryVisitor{T}"/> implementation used to process the query tree.</param>
	/// <returns>A result of type <typeparamref name="T"/> generated by the visitor.</returns>
	/// <remarks>
	/// Dispatches the execution to the <see cref="IQueryVisitor{T}.Visit(PhraseNode{T})"/> method.
	/// </remarks>
	public override T Accept(IQueryVisitor<T> visitor)
		=> visitor.Visit(this);
}