using System.Runtime.CompilerServices;
using LTU.SearchEngine.Backend.Core.SearchQueryBuilder;

namespace LTU.SearchEngine.Backend.Core.Model.ValueObjects.QueryNodes;

/// <summary>
/// Represents the base abstract class for all nodes in the Search Engine's Abstract Syntax Tree (AST).
/// </summary>
/// <typeparam name="T">The return type produced by a visitor when traversing the tree.</typeparam>
/// <remarks>
/// This class implements the "Component" part of the Visitor Design Pattern, 
/// allowing for decoupled operations on the query structure without modifying the nodes themselves.
/// </remarks>
public abstract class QueryNode<T>
{
	/// <summary>
    /// Dispatches the execution to the appropriate visit method on the provided visitor.
    /// </summary>
    /// <param name="visitor">An implementation of <see cref="IQueryVisitor{T}"/> that defines how to process this node.</param>
    /// <returns>A result of type <typeparamref name="T"/> generated by the visitor's logic.</returns>
    /// <remarks>
    /// This is the "Double Dispatch" mechanism that allows the visitor to identify 
    /// the concrete type of the node (e.g., TermNode or BinaryNode) at runtime.
    /// </remarks>
	public abstract Task<T> AcceptAsync(IQueryVisitor<T> visitor);
}
