namespace LTU.SearchEngine.Backend.Core.Model.ValueObjects.QueryNodes;


/// <summary>
/// Represents a leaf node in the query tree containing a single search term.
/// </summary>
/// <typeparam name="T">The return type produced by a visitor during tree traversal.</typeparam>
/// <remarks>
/// A TermNode is an atomic element in the Abstract Syntax Tree (AST), representing <br />
/// an unquoted keyword provided by the user.
/// </remarks>
public class TermNode<T> : QueryNode<T>
{
	public string Term { get; }

	public TermNode(string term)
	{
		if (string.IsNullOrWhiteSpace(term))
			throw new ArgumentNullException(nameof(term), "must have a value.");

		Term = term;
	}


	/// <summary>Accepts a visitor to process the term node.</summary>
	/// <param name="visitor">The <see cref="IQueryVisitor{T}"/> implementation used to process the query tree.</param>
	/// <returns>A result of type <typeparamref name="T"/> generated by the visitor.</returns>
	/// <remarks>
	/// This method performs the double-dispatch call to <see cref="IQueryVisitor{T}.Visit(TermNode{T})"/>.
	/// </remarks>
	public override T Accept(IQueryVisitor<T> visitor)
		=> visitor.Visit(this);
}
