// <auto-generated />
using System;
using LTU.SearchEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTU.SearchEngine.Infrastructure.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20260213131826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LTU.SearchEngine.Backend.Core.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCrawled")
                        .HasColumnType("TEXT");

                    b.Property<double>("PageRankScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.PageLink", b =>
                {
                    b.Property<int>("FromPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FromPageId", "ToPageId");

                    b.HasIndex("PageId");

                    b.HasIndex("ToPageId");

                    b.ToTable("PageLinks");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.PageWordFrequency", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermId1")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TfWeight")
                        .HasColumnType("REAL");

                    b.HasKey("PageId", "TermId");

                    b.HasIndex("PageId1");

                    b.HasIndex("TermId");

                    b.HasIndex("TermId1");

                    b.ToTable("PageWordFrequencies");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IdfScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.PageLink", b =>
                {
                    b.HasOne("LTU.SearchEngine.Backend.Core.Entities.Page", "FromPage")
                        .WithMany()
                        .HasForeignKey("FromPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LTU.SearchEngine.Backend.Core.Entities.Page", null)
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("PageId");

                    b.HasOne("LTU.SearchEngine.Backend.Core.Entities.Page", "ToPage")
                        .WithMany()
                        .HasForeignKey("ToPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromPage");

                    b.Navigation("ToPage");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.PageWordFrequency", b =>
                {
                    b.HasOne("LTU.SearchEngine.Backend.Core.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTU.SearchEngine.Backend.Core.Entities.Page", null)
                        .WithMany("WordFrequencies")
                        .HasForeignKey("PageId1");

                    b.HasOne("LTU.SearchEngine.Infrastructure.Entities.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LTU.SearchEngine.Infrastructure.Entities.Term", null)
                        .WithMany("PageFrequencies")
                        .HasForeignKey("TermId1");

                    b.Navigation("Page");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("LTU.SearchEngine.Backend.Core.Entities.Page", b =>
                {
                    b.Navigation("OutgoingLinks");

                    b.Navigation("WordFrequencies");
                });

            modelBuilder.Entity("LTU.SearchEngine.Infrastructure.Entities.Term", b =>
                {
                    b.Navigation("PageFrequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
